"""add cpf

Revision ID: 6bc11d769dd3
Revises: 7f8c4beee14f
Create Date: 2026-04-01 20:52:40.478067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc11d769dd3'
down_revision: Union[str, Sequence[str], None] = '7f8c4beee14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'genero')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('genero', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
