"""att nomes

Revision ID: 7f439fd4a60a
Revises: 515cfc6adeff
Create Date: 2026-03-23 11:36:56.664363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f439fd4a60a'
down_revision: Union[str, Sequence[str], None] = '515cfc6adeff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aposta_id'), table_name='aposta')
    op.drop_table('aposta')
    op.add_column('apostas', sa.Column('criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('apostas', 'premio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('apostas', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('apostas', 'criado_em')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apostas', sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('apostas', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('apostas', 'premio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('apostas', 'criacao')
    op.create_table('aposta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('premio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('criacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('aposta_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('aposta_pkey'))
    )
    op.create_index(op.f('ix_aposta_id'), 'aposta', ['id'], unique=False)
    # ### end Alembic commands ###
