"""add foto to usuario

Revision ID: 7f8c4beee14f
Revises: 7f439fd4a60a
Create Date: 2026-04-01 20:40:26.731499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8c4beee14f'
down_revision: Union[str, Sequence[str], None] = '7f439fd4a60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('foto', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('cpf', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('genero', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'genero')
    op.drop_column('usuarios', 'cpf')
    op.drop_column('usuarios', 'foto')
    # ### end Alembic commands ###
